apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket
  labels:
    app: osticket
  annotations:
    kubesailEditorUid: 4610ba2b-30ee-4d64-a282-dd018a169f8b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osticket
  template:
    metadata:
      labels:
        app: osticket
    spec:
      containers:
        - name: osticket
          image: sid4466/osticket
          imagePullPolicy: Always
          ports:
            - name: http-ports
              containerPort: 8081
